CREATE TABLE IF NOT EXISTS starred_players (
  id SERIAL PRIMARY KEY,
  scout_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  athlete_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (scout_id, athlete_id)
); 